# Site settings
title: ООО «Антилл ПРО»
description: |
  Разработка программного обеспечения для индустрии гостеприимства (HoReCa)
owner: ООО «Программные решения Антилл»
lang: ru
first_published: 2016
email: info@untill.com
url: "http://www.dev.untill.com"
baseurl: ""

# Build settings
markdown: kramdown
